### ISSUE TITLE
Add an option to the template task to produce an executable script

### ISSUE THREAD

**Issue by jmrgonza** [uwefladrich/scriptengine#46]
Just a suggestion. I think that it could be useful to add an option to the template rendering task to request that the destination file has execution permissions enabled.
I think that the same result could be achieved with a combination of a template + command task, to call "chmod +x" after the template has been rendered, but I think that the readability of the scriptengine code will be enhanced if both operations are done in the same task.

**Comment by uwefladrich** [comment]
Yes, it could make sense and simplify SE scripts if you are templating an executable script. It wouldn't be too difficult to implement either.

I wonder about two details:

- Should it just be able to set the _executable_ permission or permissions in general?
- If it sets the _executable_ permission, which mode should be used exactly (user, group, world)?

On the first point, I tend to think that it should just provide the option for _executable_. For more general setting of permissions, it would be better to use `base.command `+ `chmod` or maybe an extra task for setting permissions.

So the suggestion whould be
```yaml
- base.template:
    src: foo.sh.j2
    dst: foo.sh
    executable: yes
```

But the second issue still needs an answer.
