### ISSUE TITLE
Drop Python3.6 support

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#88]
Python3.6 is more and more difficult to maintain:
* `ModuleNotFoundError` because old `setuptools` do not have a good auto-discovery of packages
* `deepdiff` dependencies difficult to satisfy with old `pip` versions
* Python3.6 not standard on recent Github runner containers

**Comment by uwefladrich** [comment]
This would be a good issue to link with a ScriptEngine 1.0 release.

**Comment by kinow** [comment]
+1, FWIW I've been using 3.8 as minimum for newer projects when the target platform is not using an older version, but will probably switch to 3.9 or 3.10 soon. Moreover, 3.6 is EOL, 3.7's security time is almost over, and will be EOL'ed by 2023-06-27:

![image](https://user-images.githubusercontent.com/304786/223710980-0e280a68-1ab7-4cce-af18-edc46f3dcf09.png)


https://devguide.python.org/versions/

**Comment by uwefladrich** [comment]
Yes, I think the rationale for dropping 3.6 is convincing. My main issue with actually doing it right away is that SE is used on HPC machines that are sometimes rather slow to upgrade software. I am just not sure that Python 3.6 is still standard on one of the machines were it is used at the moment.
But it shouldn't be an excuse to drag on 3.6 forever. I have a plan to release 1.0 before long and drop 3.6 with this release. Maybe before summer?
